workflow optimization

diff --git a/.github/workflows/ai_pull_ci_workflow.yml b/.github/workflows/ai_pull_ci_workflow.yml
--- a/.github/workflows/ai_pull_ci_workflow.yml
+++ b/.github/workflows/ai_pull_ci_workflow.yml
@@ -4,14 +4,33 @@ name: CI Workflow for AI Search Components
 on:
   workflow_dispatch:
   workflow_call:
+    inputs:
+      versionSpec:
+        description: "The Python version to use in the environment."
+        default: "3.11"
   push:
     branches:
       - 'development'
 
+env:
+    SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
+    RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
+    STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
+    ACS_SERVICE_NAME: ${{ vars.ACS_SERVICE_NAME }}
+    AOAI_BASE_ENDPOINT: ${{ vars.AOAI_BASE_ENDPOINT }}
+    AI_STUDIO_PROJECT_NAME: ${{ vars.AI_STUDIO_PROJECT_NAME }}
+    MANAGED_IDENTITY_CLIENT_ID: ${{ vars.MANAGED_IDENTITY_CLIENT_ID }}
+    MANAGED_IDENTITY_NAME: ${{ vars.MANAGED_IDENTITY_NAME }}
+    MANAGED_IDENTITY_TENANT_ID: ${{ vars.MANAGED_IDENTITY_TENANT_ID }}
+
+permissions:
+  id-token: write
+  contents: read
 jobs:
   build-validation:
     name: Build Validation
     uses: ./.github/workflows/build_validation_workflow.yml
+
   deploy-azure-functions:
     name: Azure Functions Deployment
     runs-on: ubuntu-latest
@@ -19,46 +38,46 @@ jobs:
     steps:
       - name: Checkout Actions
         uses: actions/checkout@v1
-      - name: Export Secrets
-        uses: oNaiPs/secrets-to-env-action@v1
+
+      - uses: actions/setup-python@v4
         with:
-          secrets: ${{ toJSON(secrets) }}
-          convert: upper
-      - name: Configure Job Agent
-        uses: ./.github/actions/configure_job_agent
+            python-version: ${{ inputs.versionSpec }}
+
+      - name: Load Python Dependencies
+        shell: bash
+        run: |
+            set -e # fail on error
+            python -m pip install --upgrade pip
+            python -m pip install --upgrade -r requirements.txt
+            az version
+
+      - name: Azure login
+        uses: azure/login@v2
+        with:
+            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
+            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
+            subscription-id: ${{ env.SUBSCRIPTION_ID }}
 
       - name: Execute Azure Functions Deployment
-        uses: ./.github/actions/execute_shell_code
+        shell: bash
+        run: |
+            python -u -m mlops.deployment_scripts.deploy_azure_functions --ignore_slot
         env:
             BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
-        with:
-            script_parameter: |
-                python -u -m mlops.deployment_scripts.deploy_azure_functions --ignore_slot
-            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
-            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
-            subscription-id: ${{ env.SUBSCRIPTION_ID }}
 
       - name: Validate Azure Functions Deployment
-        uses: ./.github/actions/execute_shell_code
+        shell: bash
+        run: |
+            python -u -m mlops.deployment_scripts.run_functions --ignore_slot
         env:
             BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
-        with:
-            script_parameter: |
-                python -u -m mlops.deployment_scripts.run_functions --ignore_slot
-            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
-            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
-            subscription-id: ${{ env.SUBSCRIPTION_ID }}
 
       - name: Deploy Indexer
-        uses: ./.github/actions/execute_shell_code
+        shell: bash
+        run: |
+            python -u -m mlops.deployment_scripts.build_indexer --ignore_slot
         env:
             BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}
-        with:
-            script_parameter: |
-                python -u -m mlops.deployment_scripts.build_indexer --ignore_slot
-                client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
-            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
-            subscription-id: ${{ env.SUBSCRIPTION_ID }}
 
       - name: Get merged branch name
         id: get_branch_name
@@ -69,12 +88,8 @@ jobs:
           echo "::set-output name=sourcebranch::$SOURCEBRANCH"
 
       - name: Cleanup PR Branch
-        uses: ./.github/actions/execute_shell_code
+        shell: bash
+        run: |
+            python -u -m mlops.deployment_scripts.cleanup_pr
         env:
             BUILD_SOURCEBRANCHNAME: ${{ steps.get_branch_name.outputs.sourcebranch }}
-        with:
-            script_parameter: |
-                python -u -m mlops.deployment_scripts.cleanup_pr
-            client-id: ${{ env.MANAGED_IDENTITY_CLIENT_ID }}
-            tenant-id: ${{ env.MANAGED_IDENTITY_TENANT_ID}}
-            subscription-id: ${{ env.SUBSCRIPTION_ID }}
