check build validation

diff --git a/.github/workflows/build_validation_workflow.yml b/.github/workflows/build_validation_workflow.yml
--- a/.github/workflows/build_validation_workflow.yml
+++ b/.github/workflows/build_validation_workflow.yml
@@ -10,9 +10,22 @@ env:
 jobs:
   run-unit-tests:
     runs-on: ubuntu-latest
+    container:
+        image: aipullacr.azurecr.io/devops_container_image:latest
+        options: --user root
+        credentials:
+            username: ${{ secrets.ACR_USERNAME }}
+            password: ${{ secrets.ACR_PASSWORD }}
     steps:
       - name: Checkout
         uses: actions/checkout@v1
+
+      - name: Check Azure CLI Availability
+        run: |
+          echo "Current PATH: $PATH"
+          which az
+          ls -l $(which az) || echo "az not found in the expected directory"
+          az --version
 
       - uses: actions/setup-python@v4
         with:
